color: null
fieldLayouts:
  255c8b33-c078-4f09-9153-4b7d23f23682:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ae898cbe-e497-4843-90ec-f6d83fd8692f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 30ec3736-74c8-4d3c-aad6-7db4f0ead434 # Featured Photos
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 78e61b4b-aa26-4abd-8816-a5e5c652883e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c4e65066-f69e-47d6-af7c-f4eeeb833463 # Featured Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7d8fd7fa-7163-4459-8d90-9eea1c020b98
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 25743963-c682-433c-9442-1f382dd803b2 # Featured Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 69b540c5-ad3f-4c52-b741-96a68e280c53
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e3164e11-d937-4ed5-ac18-000641259f27 # Featured Price
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e63d6854-5169-447b-b1cd-ee2afd68dcd0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: aa8a0f8e-2eb3-4c59-b7c5-f596bbf43489
        userCondition: null
handle: featuredProducts
hasTitleField: true
icon: list
name: 'Featured Products'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
