dateModified: 1714984095
email:
  fromEmail: emile.ict@gmail.com
  fromName: pulse
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    7a2af929-f9e7-4f6a-bc8e-519c26584c61: pulse # pulse
    8f222587-c266-48e6-9967-b15b1997e199: pulse # pulse
system:
  edition: solo
  live: true
  name: pulse
  schemaVersion: 5.0.0.20
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
