defaultPlacement: end
enableVersioning: true
entryTypes:
  - bb52e698-9320-469a-9272-86aff024e282 # Products Shop
handle: shopProducts
maxAuthors: 1
name: 'Shop Products'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  7a2af929-f9e7-4f6a-bc8e-519c26584c61: # pulse
    enabledByDefault: true
    hasUrls: true
    template: shop/_entry
    uriFormat: 'shop/{slug}'
type: channel
